[package]
name = "land-channel"
version = "0.1.0"
edition = "2024"
description = "low-latency inter-thread communication"
license = "MIT"

[dependencies]
land-cpu = { path = "../cpu" }


[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
